name: C.I. with features from the project

on:
  push

jobs:
  build:
    name: Build and Install Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests for email sender
        run: |
          python test_email_sender.py
          
      - name: Run tests on the plotting data part
        run: |
          cd plot_data
          python test_plot_data.py
          
      - name: Run tests on the front-end part
        run: |
          pip install sqlalchemy
          python -m unittest discover -s Frontend/tests
