name: C.I. with features from the project

on:
  push

jobs:
  build:
    name: Build and Install Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:          
      - name: Run unittest tests
        run: |
          python -m unittest discover -s tests
